version: '3'
services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    restart: always
    volumes:
      - ./wp_data:/var/www/html
      - ./wp_logs:/var/log/apache2
    ports:
      - '9190:80'  
    environment:
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_db_password
      WORDPRESS_DB_HOST: db:3306
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '9306:3306'  
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_db_password
volumes:
  wp_data:
  db_data:
  wp_logs:
